[project]
name = "pixi_demo"
version = "1.0.0"
description = "This demo shows how to use pixi to build a machine learning pipeline."
channels = ["conda-forge"]
platforms = ["win-64"]

[environments]
default = { features = ["base"]}
rrr = { features = ["ggplot"]}

[feature.ggplot.tasks]
explorer = "Rscript src/iris/plot_iris.r"

[tasks]
get_data = "python src/iris/get_data.py"
explore = { cmd = ["python", "src/iris/explore.py"], depends-on = ["get_data"] }
explain = "python src/iris/explain.py"
train = "python src/iris/train.py"
all = { depends-on = ["explore", "train", "explain" ] }

[feature.base.dependencies]
python = "3.10.*"
scikit-learn = ">=1.5.2,<2"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
yellowbrick = ">=1.5,<2"

[feature.ggplot.dependencies]
r-base = ">=4.1.3,<5"
r-essentials = ">=4.4,<5"

